import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "zh-HK" | "zh-CN";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// ========== Translations ==========
const translations: Record<Language, Record<string, string>> = {
  "zh-HK": {
    // Navigation
    "nav.services": "服務方案",
    "nav.story": "點解有張地圖",
    "nav.templates": "免費模板",
    "nav.contact": "免費咨詢",
    "nav.fundOverview": "資助一覽",
    "nav.freeAssessment": "免費評估",
    "nav.pricing": "訂閱方案",
    "nav.freeResources": "免費資源",
    
    // Hero
    "hero.title": "核芯機器",
    "hero.subtitle": "港澳青年北上前海創業加速器",
    "hero.tagline": "1站式註冊 + 補貼 + AI工具",
    "hero.description": "我哋係專業嘅中港創業落地服務平台，幫助香港創業者輕鬆完成前海公司註冊、補貼申請同 AI 工具落地。我行過嘅路，教你避坑。",
    "hero.cta.primary": "免費咨詢",
    "hero.cta.secondary": "下載免費模板",
    
    // Services
    "services.title": "服務方案",
    "services.subtitle": "為你度身訂造嘅創業落地方案",
    "services.basic.title": "基礎包",
    "services.basic.price": "HK$10,000",
    "services.basic.description": "適合初創企業，快速完成註冊同補貼申請",
    "services.basic.feature1": "前海公司註冊全流程",
    "services.basic.feature2": "補貼申請文件準備",
    "services.basic.feature3": "政策咨詢與指導",
    "services.basic.feature4": "銀行開戶協助",
    "services.basic.feature5": "社保繳納指引",
    "services.vip.title": "VIP包",
    "services.vip.price": "HK$20,000+",
    "services.vip.description": "全方位支援，包含 AI 內容營銷方案",
    "services.vip.feature1": "基礎包所有服務",
    "services.vip.feature2": "AI 工具落地與培訓",
    "services.vip.feature3": "內容營銷策略制定",
    "services.vip.feature4": "社交媒體運營指導",
    "services.vip.feature5": "持續技術支援（3個月）",
    "services.cta": "立即咨詢",
    
    // Story
    "story.title": "點解有張地圖",
    "story.subtitle": "一個38歲香港人嘅歸零重啟",
    "story.age": "38歲",
    "story.intro": "2023年，我38歲，在香港職場遇到瓶頸。我決定北上前海，從零開始。來到這裡發現，最難的並非做生意，而是搞清哪裡有資金領取、如何領取。我用了9個月自己摸索，走遍了所有彎路。這張地圖，就是我用心血繪製出來的。",
    "story.challenge.title": "職場瓶頸",
    "story.challenge.content": "38歲，從事了十多年金融和科技行業，發現香港的上升空間越來越窄。想轉型，但成本太高、風險太大。我問自己：是否要這樣做到退休？",
    "story.solution.title": "歸零出發",
    "story.solution.content": "我帶著兩個行李箱，一個人搬去前海。從找寫字樓、註冊公司、到搞清哪些補貼適合我申請——全部親自處理。走錯路、填錯表、漏交文件，每樣都經歷過。",
    "story.vision.title": "畫張地圖俾你",
    "story.vision.content": "我發現，九成香港創業者都和我一樣：不了解有什麼資助、不懂得如何申請、擔心受騙。所以我創立了 Core Machine——並非代你前行，而是繪製地圖給你，讓你學會自己前行。因為最可靠的導航，是你自己學會看路。",
    
    // Founder story section
    "founder.greeting": "我 38 歲，由香港走到前海",
    "founder.problem.title": "九成香港創業者都遇到這三個問題",
    "founder.problem.card1": "不了解有什麼資助適合自己",
    "founder.problem.card2": "文件繁復，不知如何填寫",
    "founder.problem.card3": "擔心受騙，對中介缺乏信任",
    "founder.target.title": "我哋為呢種人而設",
    "founder.target.checklist": "✅ 你係我哋嘅目標客戶如果：",
    "founder.notTarget.title": "❌ 你唔係我哋嘅目標客戶如果：",
    "founder.mission.title": "我哋存在，係為咗縮小資訊差距",
    "founder.dualModel.title": "雙模型把關，你嘅文件有兩次 AI 審閱",
    "founder.why.title": "點解係我？我可以幫你乜？",
    "founder.why.q1": "Q1：點解要放棄香港嘅一切？",
    "founder.why.q2": "Q2：北上之後遇到咩困難？",
    "founder.why.q3": "Q3：點解我要做 Core Machine？",
    "founder.achievements.title": "我哋做到咗乜",
    
    // Templates
    "templates.title": "免費 AI 模板下載",
    "templates.subtitle": "專業文件模板，助你快速完成申請",
    "templates.subsidy.title": "前海補貼申請文件模板",
    "templates.subsidy.description": "包含完整嘅申請資格說明、所需文件清單同線上申請步驟，繁簡雙語版本。",
    "templates.statement.title": "個人陳述專業模板",
    "templates.statement.description": "專業撰寫指引，幫你突出個人優勢，提高申請成功率。",
    "templates.download": "下載模板",
    "templates.email.hint": "留低郵箱，獲取更多創業資訊",
    "templates.email.placeholder": "電子郵件（可選）",
    
    // AI Generator
    "ai.title": "🤖 AI 智能生成個人化文件",
    "ai.subtitle": "填寫基本資料，Johnny 即時為你生成專業申請文件",
    "ai.description": "AI 文件生成器，輸入資料即時生成專業申請文件或個人陳述",
    "ai.section.title": "AI 智能生成（新版）",
    "ai.section.description": "輸入你的基本資料，AI 即時生成個人化補貼申請文件或個人陳述",
    "ai.section.cta": "立即 AI 生成",
    "ai.form.name": "姓名",
    "ai.form.name.placeholder": "請輸入你的姓名",
    "ai.form.age": "年齡",
    "ai.form.education": "最高學歷",
    "ai.education.associate": "副學士 / 高級文憑",
    "ai.education.bachelor": "學士學位",
    "ai.education.master": "碩士學位",
    "ai.education.doctorate": "博士學位",
    "ai.form.industry": "香港從事行業",
    "ai.form.industry.placeholder": "例如：金融、科技、零售、媒體",
    "ai.form.experience": "工作經驗摘要",
    "ai.form.experience.placeholder": "例如：過去8年喺香港從事FinTech行業，曾任職產品經理...",
    "ai.form.identity": "你係創業者定受薪者？",
    "ai.identity.founder": "創業者",
    "ai.identity.employee": "受薪者",
    "ai.form.companyName": "公司名稱（創辦中/已成立）",
    "ai.form.companyName.placeholder": "例如：Core Machine Limited",
    "ai.form.targetCompany": "目標入職公司",
    "ai.form.targetCompany.placeholder": "例如：前海某科技公司",
    "ai.form.motivation": "決心北上發展的原因",
    "ai.form.motivation.placeholder": "例如：香港樓價高、事業遇到瓶頸、大灣區機遇前所未有...",
    "ai.form.goals": "申請目標",
    "ai.goals.subsidy": "前海港澳青年補貼",
    "ai.goals.opc": "OPC 8個0資助",
    "ai.goals.both": "兩樣都要",
    "ai.form.email": "電郵（可選）",
    "ai.form.email.placeholder": "我們會發送文件副本到你的郵箱",
    "ai.form.optional": "可選",
    "ai.form.documentType": "文件類型",
    "ai.form.documentType.subsidy": "補貼申請表",
    "ai.form.documentType.statement": "個人陳述",
    "ai.form.background": "你的背景",
    "ai.form.background.placeholder": "例如：大學畢業，主修金融...",
    "ai.form.businessIdea": "創業方向",
    "ai.form.businessIdea.placeholder": "例如：想做跨境電商...",
    "ai.form.targetMarket": "目標市場",
    "ai.form.targetMarket.placeholder": "例如：粵港澳大灣區...",
    "ai.form.fundingNeeds": "資金需求",
    "ai.form.fundingNeeds.placeholder": "例如：希望申請 10 萬...",
    "ai.form.otherInfo": "其他資訊",
    "ai.form.otherInfo.placeholder": "任何其他有助於 AI 生成文件的資料...",
    "ai.form.generating": "生成中...",
    "ai.form.generate": "生成文件",
    "ai.form.copy": "複製",
    "ai.form.download": "下載",
    "ai.email.label": "你的 email（已訂閱會員）",
    "ai.email.optional": "可選",
    "ai.email.hint": "已訂閱的話填寫，會扣 credit",
    "ai.next": "下一步",
    "ai.back": "返回",
    "ai.generate.subsidy": "生成補貼申請",
    "ai.generate.statement": "生成個人陳述",
    "ai.generating": "Johnny 正在為你生成中...",
    "ai.success": "文件生成成功！",
    "ai.copied": "已複製到剪貼板",
    "ai.tip": "💡 提示：生成嘅文件可以複製或下載...",
    "ai.fillFormToStart": "填寫左邊嘅表單開始生成",
    "ai.willGenerateForYou": "AI 會根據你嘅信息生成專業文件",
    "ai.footer.note": "文件由 Core Machine AI 即時生成，可直接用於申請",
    "ai.footer.whatsapp": "需要人工幫助？WhatsApp 聯絡我哋",

    // Stripe
    "stripe.pay": "HK$XXX 立即訂閱",
    "stripe.paymentPending": "連接 Stripe 中...",
    "stripe.paymentFailed": "啟動付款失敗，請稍後再試",
    "stripe.connecting": "連接 Stripe...",
    
    // Contact
    "contact.title": "免費咨詢",
    "contact.subtitle": "填寫表單，我哋會儘快聯絡你",
    "contact.form.name": "姓名",
    "contact.form.name.placeholder": "請輸入你嘅姓名",
    "contact.form.contact": "聯絡方式",
    "contact.form.contact.placeholder": "電話或微信號",
    "contact.form.email": "電子郵件（可選）",
    "contact.form.email.placeholder": "example@email.com",
    "contact.form.needs": "你嘅需求",
    "contact.form.needs.placeholder": "請詳細描述你嘅需求，例如：想註冊前海公司、申請補貼、了解 AI 工具等",
    "contact.form.submit": "提交咨詢",
    "contact.form.submitting": "提交中...",
    "contact.success": "提交成功！我哋會儘快聯絡你。",
    "contact.error": "提交失敗，請稍後再試。",
    
    // Pricing Page
    "pricing.subtitle": "靈活方案，適合不同階段創業者",
    "pricing.title": "訂閱方案",
    "pricing.free.tag": "免費",
    "pricing.free.title": "免費資源",
    "pricing.free.description": "適合任何階段創業者，無需付款即可使用",
    "pricing.free.feature1": "資助配對評估",
    "pricing.free.feature2": "年齡/地區篩選",
    "pricing.free.feature3": "截止日期提示",
    "pricing.free.feature4": "申請流程指南",
    "pricing.free.feature5": "AI 評估工具",
    "pricing.free.cta": "了解更多",
    "pricing.ai.tag": "AI 體驗",
    "pricing.ai.title": "AI 體驗",
    "pricing.ai.description": "輸入電郵，體驗 AI 文件生成",
    "pricing.ai.emailPlaceholder": "your@email.com",
    "pricing.ai.cta": "立即體驗",
    "pricing.starter.tag": "最受歡迎",
    "pricing.starter.title": "Starter",
    "pricing.starter.price": "HK$38/月",
    "pricing.starter.priceYearly": "或 HK$380/年",
    "pricing.starter.description": "完整功能，適合個人創業者",
    "pricing.starter.feature1": "無限次 AI 文件生成",
    "pricing.starter.feature2": "真人代辦審閱",
    "pricing.starter.feature3": "優先客戶支援",
    "pricing.starter.feature4": "每月策略咨詢（30分鐘）",
    "pricing.starter.feature5": "文件版本保存",
    "pricing.starter.cta": "立即開始",
    "pricing.starter.changeEmail": "更改 email",
    "pricing.starter.savings": "慳 15%",
    "pricing.starter.yearly": "Starter 年費",
    "pricing.starter.monthlyEquiv": "相當於每月 HK$32",
    "pricing.starter.yearlySupport": "年費專享：優先客戶支援",
    "pricing.starter.subscribeYearly": "立即訂閱年費",
    "pricing.pro.tag": "旗艦",
    "pricing.pro.title": "Pro",
    "pricing.pro.price": "HK$128/月",
    "pricing.pro.priceMonthly": "每月",
    "pricing.pro.description": "企業級支援，適合認真擴展業務的你",
    "pricing.pro.feature1": "Starter 所有功能",
    "pricing.pro.feature2": "無限次真人審閱",
    "pricing.pro.feature3": "全程代辦支援",
    "pricing.pro.feature4": "無限次策略咨詢",
    "pricing.pro.feature5": "優先審批通道",
    "pricing.pro.bonus": "附送公司註冊指南",
    "pricing.pro.cta": "聯絡我們",
    "pricing.pro.changeEmail": "更改 email",
    "pricing.pro.savings": "慳 15%",
    "pricing.pro.onetime": "一次性",
    "pricing.pro.choosePayment": "選擇付款方式",
    "pricing.enterprise": "企業方案",
    "pricing.enterpriseCTA": "先做免費評估",
    "pricing.stripePay": "Stripe 安全付款",
    "pricing.cancelAnytime": "隨時可取消",
    "pricing.docReview": "專業文件審閱",
    "pricing.enterprise.cta": "聯絡我們",
    "pricing.faq.title": "常見問題",
    "pricing.faq.q1": "付款安全嗎？",
    "pricing.faq.q2": "可以隨時取消嗎？",
    "pricing.faq.q3": "文件能用於正式申請嗎？",
    "pricing.faq.a1": "我們使用 Stripe 處理付款，銀行級加密，完全安全。",
    "pricing.faq.a2": "可以隨時取消，取消後下一個週期不會再收費。",
    "pricing.faq.a3": "是的，我們的文件由專業人士審閱，可直接用於正式申請。",

    // Fund overview
    "fund.title": "中港創業資助一覽",
    "fund.subtitle": "精準配對 · 最高效的路徑補貼",
    "fund.cta": "評估適合你的資助",
    "fund.viewAll": "查看全部資助",
    "fund.tab.qianhai": "前海 · 深圳",
    "fund.tab.hongkong": "香港",
    "fund.tab.gba": "大灣區",

    // Fund Card 1: OPC
    "fund.opc.name": "前海OPC「獨行俠禮包」",
    "fund.opc.tag": "AI創業首選",
    "fund.opc.amount": "最高 200㎡ 空間 + 50P 算力",
    "fund.opc.bonus": "人才獎勵最高 60 萬",
    "fund.opc.description": "專為 AI 獨行俠設計的一人公司創業基地。3 個月主流大模型免費試用，讓你專注產品開發。",
    "fund.opc.eligible": "• 港澳居民（18-45歲）\n• AI / 數碼科技相關項目優先\n• 已注冊或計劃注冊前海公司",

    // Fund Card 2: 深圳智能券
    "fund.smartcoupon.name": "深圳智能券 · 訓力券 · 模型券",
    "fund.smartcoupon.tag": "算力補貼",
    "fund.smartcoupon.amount": "最高 1000 萬算力補貼",
    "fund.smartcoupon.bonus": "200萬 模型券 + 200萬 語料券",
    "fund.smartcoupon.description": "深圳市 AI 訓練與部署專項補貼。入駐 OPC 後自動匹配，後續可持續申請。",
    "fund.smartcoupon.eligible": "• OPC 園區入駐企業\n• AI 訓練或模型部署需求\n• 深圳有效工商登記",

    // Fund Card 3: 鯤鵬
    "fund.kunpeng.name": "鯤鵬青年創新創業項目",
    "fund.kunpeng.tag": "創新創業",
    "fund.kunpeng.amount": "最高 5 萬獎勵 + 100 萬研發資助",
    "fund.kunpeng.bonus": "導師資源 + 產業對接",
    "fund.kunpeng.description": "面向 35 歲以下青年創業者的創新項目資助。重點支持信息技術、生物醫藥、新能源等領域。",
    "fund.kunpeng.eligible": "• 35 歲以下青年創業者\n• 具備創新技術或商業模式\n• 項目具有市場化潛力",

    // Fund Card 4: Cyberport
    "fund.cyberport.name": "Cyberport數碼港孵化計劃",
    "fund.cyberport.tag": "香港旗艦孵化",
    "fund.cyberport.amount": "最高 50 萬孵化資助",
    "fund.cyberport.bonus": "免費辦公室 + 導師網絡",
    "fund.cyberport.description": "香港數碼港旗艦孵化項目，專為 AI 和數碼科技初創設計，提供全方位創業支援。",
    "fund.cyberport.eligible": "• AI / 數碼科技相關項目\n• 香港注冊公司或計劃在香港注冊\n• 具有跨境發展潛力（如 GBA）",

    // Fund Card 5: HKSTP
    "fund.hkstp.name": "科技園Incu-Tech計劃",
    "fund.hkstp.tag": "科技企業",
    "fund.hkstp.amount": "最高百萬資助 + 資源對接",
    "fund.hkstp.bonus": "科研設施 + 人才網絡",
    "fund.hkstp.description": "香港科技園 Incu-Tech 計劃，為科技初創提供資助、辦公室和科研設施支援。",
    "fund.hkstp.eligible": "• 科技初創企業\n• 持有香港身份證的創業者\n• 具備核心技術或 IP",

    // Fund Card 6: ITF
    "fund.itf.name": "創新及科技基金AI補貼",
    "fund.itf.tag": "創科支援",
    "fund.itf.amount": "最高 70% 算力補貼",
    "fund.itf.bonus": "研發資助 + 技術支持",
    "fund.itf.description": "創新及科技基金下的 AI 專項補貼計劃，資助企業採用和開發 AI 技術。",
    "fund.itf.eligible": "• 香港注冊的中小企\n• AI 技術應用或研發項目\n• 具有技術團隊或合作夥伴",

    // Fund Card 7: GBA
    "fund.gba.name": "大灣區青年創業基金",
    "fund.gba.tag": "跨境創業",
    "fund.gba.amount": "香港青年大灣區創業專項資助",
    "fund.gba.bonus": "額外配套獎勵 + 落地支援",
    "fund.gba.description": "專為香港青年在大灣區創業設立的專項基金，提供資金和落地支援。",
    "fund.gba.eligible": "• 香港永久居民\n• 在大灣區內地城市創業\n• 18-40 歲青年創業者",

    // Fund Card 8: 粵港澳青年
    "fund.youth.name": "粵港澳青年創業計劃",
    "fund.youth.tag": "青年創業",
    "fund.youth.amount": "生活補貼 + 創業支援",
    "fund.youth.bonus": "孵化服務 + 導師指導",
    "fund.youth.description": "支持粵港澳三地青年在內地創業的綜合性資助計劃，包含生活補貼和創業支援。",
    "fund.youth.eligible": "• 粵港澳三地青年（18-45歲）\n• 在內地創業的港澳青年\n• 已開展創業項目或已有商業計劃",

    // Fund process
    "fund.process.title": "申請流程",
    "fund.process.step1.title": "評估配對",
    "fund.process.step1.desc": "根據你的項目和背景，評估最適合的資助方案",
    "fund.process.step2.title": "准備文件",
    "fund.process.step2.desc": "協助准備商業計劃書、財務預測等申請文件",
    "fund.process.step3.title": "遞交申請",
    "fund.process.step3.desc": "代為遞交申請，確保資料完整合規",
    "fund.process.step4.title": "跟進管理",
    "fund.process.step4.desc": "跟進審批進度，及時補充材料直至獲批",

    // Fund docs
    "fund.docs.title": "必備文件清單",
    "fund.docs.business": "商業計劃書（Word/PDF）",
    "fund.docs.reg": "公司注冊證書副本",
    "fund.docs.id": "創業者身份證明文件",
    "fund.docs.financial": "財務預測或現有財務報表",
    "fund.docs.tech": "技術/產品介紹（如有）",
    "fund.docs.other": "其他輔助材料（專利、獎項、合作意向書等）",

    // FreeResources
    "free.title": "免費資源",
    "free.subtitle": "回答幾條簡單問題，立即知道邊個資助啱你",
    "free.cta": "立即評估資格",
    "free.tryAI": "試用 AI 生成文件",
    "free.ready": "準備好開始？",
    "free.pricing": "查看定價",
    "free.consult": "免費咨詢",

    // Footer
    "footer.company": "Core Machine Limited",
    "footer.tagline": "港澳青年北上前海創業加速器",
    "footer.description": "專業嘅中港創業落地服務平台",
    "footer.contact.title": "聯絡我哋",
    "footer.contact.email": "iocoremachine@gmail.com",
    "footer.contact.website": "coremachine.io",
    "footer.services.title": "服務",
    "footer.services.registration": "公司註冊",
    "footer.services.subsidy": "補貼申請",
    "footer.services.ai": "AI 工具",
    "footer.services.marketing": "內容營銷",
    "footer.resources.title": "資源",
    "footer.resources.templates": "免費模板",
    "footer.resources.blog": "創業指南",
    "footer.resources.faq": "常見問題",
    "footer.legal.title": "法律",
    "footer.legal.terms": "服務條款",
    "footer.legal.privacy": "私隱政策",
    "footer.copyright": "© 2026 Core Machine Limited. 版權所有。",
  },
  "zh-CN": {
    // Navigation
    "nav.services": "服务方案",
    "nav.story": "為什麼有張地图",
    "nav.templates": "免费模板",
    "nav.contact": "免费咨询",
    "nav.freeResources": "免费资源",
    "nav.pricing": "订阅方案",
    "nav.fundOverview": "资助一览",
    "nav.freeAssessment": "免费评估",
    
    // Hero
    "hero.title": "核芯机器",
    "hero.subtitle": "港澳青年北上前海创业加速器",
    "hero.tagline": "1站式注册 + 补贴 + AI工具",
    "hero.description": "我们是专业的中港创业落地服务平台，帮助香港创业者轻松完成前海公司注册、补贴申请和 AI 工具落地。我走过的路，教你避坑。",
    "hero.cta.primary": "免费咨询",
    "hero.cta.secondary": "下载免费模板",
    
    // Services
    "services.title": "服务方案",
    "services.subtitle": "为您量身定制的创业落地方案",
    "services.basic.title": "基础包",
    "services.basic.price": "HK$10,000",
    "services.basic.description": "适合初创企业，快速完成注册和补贴申请",
    "services.basic.feature1": "前海公司注册全流程",
    "services.basic.feature2": "补贴申请文件准备",
    "services.basic.feature3": "政策咨询与指导",
    "services.basic.feature4": "银行开户协助",
    "services.basic.feature5": "社保缴纳指引",
    "services.vip.title": "VIP包",
    "services.vip.price": "HK$20,000+",
    "services.vip.description": "全方位支持，包含 AI 内容营销方案",
    "services.vip.feature1": "基础包所有服务",
    "services.vip.feature2": "AI 工具落地与培训",
    "services.vip.feature3": "内容营销策略制定",
    "services.vip.feature4": "社交媒体运营指导",
    "services.vip.feature5": "持续技术支持（3个月）",
    "services.cta": "立即咨询",
    
    // Story
    "story.title": "為什麼有張地图",
    "story.subtitle": "一個38歲香港人的歸零重啟",
    "story.age": "38歲",
    "story.intro": "2023年，我38歲，在香港職場撞到天花板。我決定北上前海，從零開始。下來發現，最難的不是做生意，是搞清哪裡有錢拿、怎麼拿。我用了9個月自己摸索，走遍所有彎路。這張地圖，就是我用血淚畫出來的。",
    "story.challenge.title": "職場瓶頸",
    "story.challenge.content": "38歲，做過10幾年金融和科技行業，發現香港的上升空間越來越窄。想轉型，但成本太高、風險太大。我問自己：是不是要這樣做到退休？",
    "story.solution.title": "歸零出發",
    "story.solution.content": "我帶著兩個行李箱，一個人搬去前海。從找寫字樓、註冊公司、到搞清哪些補貼適合我申請——全部自己來。走錯路、填錯表、漏交文件，樣樣試過。",
    "story.vision.title": "畫張地圖給你",
    "story.vision.content": "我發現，九成香港創業者都和我一樣：不知道有什麼資助、不會怎麼申請、怕被騙。所以我做了 Core Machine——不是替你走，是畫張地圖給你，讓你自己會走。因為最可靠的導航，是你自己學會看路。",
    
    // Founder story section
    "founder.greeting": "我 38 歲，由香港走到前海",
    "founder.problem.title": "九成香港創業者都遇到這三個問題",
    "founder.problem.card1": "不了解有什麼資助適合自己",
    "founder.problem.card2": "文件繁復，不知如何填寫",
    "founder.problem.card3": "擔心受騙，對中介缺乏信任",
    "founder.target.title": "我哋為呢種人而設",
    "founder.target.checklist": "✅ 你係我哋嘅目標客戶如果：",
    "founder.notTarget.title": "❌ 你唔係我哋嘅目標客戶如果：",
    "founder.mission.title": "我哋存在，係為咗縮小資訊差距",
    "founder.dualModel.title": "雙模型把關，你嘅文件有兩次 AI 審閱",
    "founder.why.title": "點解係我？我可以幫你乜？",
    "founder.why.q1": "Q1：點解要放棄香港嘅一切？",
    "founder.why.q2": "Q2：北上之後遇到咩困難？",
    "founder.why.q3": "Q3：點解我要做 Core Machine？",
    "founder.achievements.title": "我哋做到咗乜",
    
    // Templates
    "templates.title": "免费 AI 模板下载",
    "templates.subtitle": "专业文件模板，助您快速完成申请",
    "templates.subsidy.title": "前海补贴申请文件模板",
    "templates.subsidy.description": "包含完整的申请资格说明、所需文件清单和线上申请步骤，繁简双语版本。",
    "templates.statement.title": "个人陈述专业模板",
    "templates.statement.description": "专业撰写指引，帮您突出个人优势，提高申请成功率。",
    "templates.download": "下载模板",
    "templates.email.hint": "留下邮箱，获取更多创业资讯",
    "templates.email.placeholder": "电子邮件（可选）",
    
    // AI Generator
    "ai.title": "🤖 AI 智能生成个人化文件",
    "ai.subtitle": "填写基本资料，Johnny 即时为您生成专业申请文件",
    "ai.description": "AI 文件生成器，输入资料即时生成专业申请文件或个人陈述",
    "ai.section.title": "AI 智能生成（新版）",
    "ai.section.description": "输入您的基本资料，AI 即时生成个人化补贴申请文件或个人陈述",
    "ai.section.cta": "立即 AI 生成",
    "ai.form.name": "姓名",
    "ai.form.name.placeholder": "请输入您的姓名",
    "ai.form.age": "年龄",
    "ai.form.education": "最高学历",
    "ai.education.associate": "副学士 / 高级文凭",
    "ai.education.bachelor": "学士学位",
    "ai.education.master": "硕士学位",
    "ai.education.doctorate": "博士学位",
    "ai.form.industry": "香港从事行业",
    "ai.form.industry.placeholder": "例如：金融、科技、零售、媒体",
    "ai.form.experience": "工作经验摘要",
    "ai.form.experience.placeholder": "例如：过去8年在香港从事FinTech行业，曾任职产品经理...",
    "ai.form.identity": "您是创业者还是受薪者？",
    "ai.identity.founder": "创业者",
    "ai.identity.employee": "受薪者",
    "ai.form.companyName": "公司名称（创办中/已成立）",
    "ai.form.companyName.placeholder": "例如：Core Machine Limited",
    "ai.form.targetCompany": "目标入职公司",
    "ai.form.targetCompany.placeholder": "例如：前海某科技公司",
    "ai.form.motivation": "决心北上发展的原因",
    "ai.form.motivation.placeholder": "例如：香港楼价高、事业遇到瓶颈、大湾区机遇前所未有...",
    "ai.form.goals": "申请目标",
    "ai.goals.subsidy": "前海港澳青年补贴",
    "ai.goals.opc": "OPC 8个0资助",
    "ai.goals.both": "两样都要",
    "ai.form.email": "电邮（可选）",
    "ai.form.email.placeholder": "我们将发送文件副本到您的邮箱",
    "ai.form.optional": "可选",
    "ai.form.documentType": "文件类型",
    "ai.form.documentType.subsidy": "补贴申请表",
    "ai.form.documentType.statement": "个人陈述",
    "ai.form.background": "您的背景",
    "ai.form.background.placeholder": "例如：大學畢業，主修金融...",
    "ai.form.businessIdea": "创业方向",
    "ai.form.businessIdea.placeholder": "例如：想做跨境电商...",
    "ai.form.targetMarket": "目标市场",
    "ai.form.targetMarket.placeholder": "例如：粤港澳大湾区...",
    "ai.form.fundingNeeds": "资金需求",
    "ai.form.fundingNeeds.placeholder": "例如：希望申请 10 万...",
    "ai.form.otherInfo": "其他信息",
    "ai.form.otherInfo.placeholder": "任何其他有助于 AI 生成文件的信息...",
    "ai.form.generating": "生成中...",
    "ai.form.generate": "生成文件",
    "ai.form.copy": "复制",
    "ai.form.download": "下载",
    "ai.email.label": "您的 email（已订阅会员）",
    "ai.email.optional": "可选",
    "ai.email.hint": "已订阅的话填写，会扣 credit",
    "ai.next": "下一步",
    "ai.back": "返回",
    "ai.generate.subsidy": "生成补贴申请",
    "ai.generate.statement": "生成个人陈述",
    "ai.generating": "Johnny 正在为您生成中...",
    "ai.success": "文件生成成功！",
    "ai.copied": "已复制到剪贴板",
    "ai.tip": "💡 提示：生成的文件可以复制或下载...",
    "ai.fillFormToStart": "填写左边的表单开始生成",
    "ai.willGenerateForYou": "AI 会根据您的信息生成专业文件",
    "ai.footer.note": "文件由 Core Machine AI 即时生成，可直接用于申请",
    "ai.footer.whatsapp": "需要人工帮助？WhatsApp 联络我们",

    // Stripe
    "stripe.pay": "HK$XXX 立即订阅",
    "stripe.paymentPending": "连接 Stripe 中...",
    "stripe.paymentFailed": "启动付款失败，请稍后重试",
    "stripe.connecting": "连接 Stripe...",
    
    // Contact
    "contact.title": "免费咨询",
    "contact.subtitle": "填写表单，我们会尽快联系您",
    "contact.form.name": "姓名",
    "contact.form.name.placeholder": "请输入您的姓名",
    "contact.form.contact": "联系方式",
    "contact.form.contact.placeholder": "电话或微信号",
    "contact.form.email": "电子邮件（可选）",
    "contact.form.email.placeholder": "example@email.com",
    "contact.form.needs": "您的需求",
    "contact.form.needs.placeholder": "请详细描述您的需求，例如：想注册前海公司、申请补贴、了解 AI 工具等",
    "contact.form.submit": "提交咨询",
    "contact.form.submitting": "提交中...",
    "contact.success": "提交成功！我们会尽快联系您。",
    "contact.error": "提交失败，请稍后再试。",
    
    // Pricing Page
    "pricing.subtitle": "灵活方案，适合不同阶段创业者",
    "pricing.title": "订阅方案",
    "pricing.free.tag": "免费",
    "pricing.free.title": "免费资源",
    "pricing.free.description": "适合任何阶段创业者，无需付款即可使用",
    "pricing.free.feature1": "资助配对评估",
    "pricing.free.feature2": "年龄/地区筛选",
    "pricing.free.feature3": "截止日期提示",
    "pricing.free.feature4": "申请流程指南",
    "pricing.free.feature5": "AI 评估工具",
    "pricing.free.cta": "了解更多",
    "pricing.ai.tag": "AI 体验",
    "pricing.ai.title": "AI 体验",
    "pricing.ai.description": "输入电邮，体验 AI 文件生成",
    "pricing.ai.emailPlaceholder": "your@email.com",
    "pricing.ai.cta": "立即体验",
    "pricing.starter.tag": "最受欢迎",
    "pricing.starter.title": "Starter",
    "pricing.starter.price": "HK$38/月",
    "pricing.starter.priceYearly": "或 HK$380/年",
    "pricing.starter.description": "完整功能，适合个人创业者",
    "pricing.starter.feature1": "无限次 AI 文件生成",
    "pricing.starter.feature2": "真人代办审阅",
    "pricing.starter.feature3": "优先客户支援",
    "pricing.starter.feature4": "每月策略咨询（30分钟）",
    "pricing.starter.feature5": "文件版本保存",
    "pricing.starter.cta": "立即开始",
    "pricing.starter.changeEmail": "更改 email",
    "pricing.starter.savings": "省 15%",
    "pricing.starter.yearly": "Starter 年费",
    "pricing.starter.monthlyEquiv": "相当于每月 HK$32",
    "pricing.starter.yearlySupport": "年费专享：优先客户支援",
    "pricing.starter.subscribeYearly": "立即订阅年费",
    "pricing.pro.tag": "旗舰",
    "pricing.pro.title": "Pro",
    "pricing.pro.price": "HK$128/月",
    "pricing.pro.priceMonthly": "每月",
    "pricing.pro.description": "企业级支援，适合认真扩展业务的你",
    "pricing.pro.feature1": "Starter 所有功能",
    "pricing.pro.feature2": "无限次真人审阅",
    "pricing.pro.feature3": "全程代办支援",
    "pricing.pro.feature4": "无限次策略咨询",
    "pricing.pro.feature5": "优先审批通道",
    "pricing.pro.bonus": "附送公司注册指南",
    "pricing.pro.cta": "联络我们",
    "pricing.pro.changeEmail": "更改 email",
    "pricing.pro.savings": "省 15%",
    "pricing.pro.onetime": "一次性",
    "pricing.pro.choosePayment": "选择付款方式",
    "pricing.enterprise": "企业方案",
    "pricing.enterpriseCTA": "先做免费评估",
    "pricing.stripePay": "Stripe 安全付款",
    "pricing.cancelAnytime": "随时可取消",
    "pricing.docReview": "专业文件审阅",
    "pricing.enterprise.cta": "联络我们",
    "pricing.faq.title": "常见问题",
    "pricing.faq.q1": "付款安全吗？",
    "pricing.faq.q2": "可以随时取消吗？",
    "pricing.faq.q3": "文件能用于正式申请吗？",
    "pricing.faq.a1": "我们使用 Stripe 处理付款，银行级加密，完全安全。",
    "pricing.faq.a2": "可以随时取消，取消后下一个周期不会再收费。",
    "pricing.faq.a3": "是的，我们的文件由专业人士审阅，可直接用于正式申请。",

    // Fund overview
    "fund.title": "中港创业资助一览",
    "fund.subtitle": "精准配对 · 最高效的路径补贴",
    "fund.cta": "评估适合你的资助",
    "fund.viewAll": "查看全部资助",
    "fund.tab.qianhai": "前海 · 深圳",
    "fund.tab.hongkong": "香港",
    "fund.tab.gba": "大湾区",

    // Fund Card 1: OPC
    "fund.opc.name": "前海OPC「独行侠礼包」",
    "fund.opc.tag": "AI创业首选",
    "fund.opc.amount": "最高 200㎡ 空间 + 50P 算力",
    "fund.opc.bonus": "人才奖励最高 60 万",
    "fund.opc.description": "专为 AI 独行侠设计的一人公司创业基地。3 个月主流大模型免费试用，让你专注产品开发。",
    "fund.opc.eligible": "• 港澳居民（18-45岁）\n• AI / 数码科技相关项目优先\n• 已注册或计划注册前海公司",

    // Fund Card 2: 深圳智能券
    "fund.smartcoupon.name": "深圳智能券 · 训力券 · 模型券",
    "fund.smartcoupon.tag": "算力补贴",
    "fund.smartcoupon.amount": "最高 1000 万算力补贴",
    "fund.smartcoupon.bonus": "200万 模型券 + 200万 语料券",
    "fund.smartcoupon.description": "深圳市 AI 训练与部署专项补贴。入驻 OPC 后自动匹配，后续可持续申请。",
    "fund.smartcoupon.eligible": "• OPC 园区入驻企业\n• AI 训练或模型部署需求\n• 深圳有效工商登记",

    // Fund Card 3: 鯤鵬
    "fund.kunpeng.name": "鲲鹏青年创新创业项目",
    "fund.kunpeng.tag": "创新创业",
    "fund.kunpeng.amount": "最高 5 万奖励 + 100 万研发资助",
    "fund.kunpeng.bonus": "导师资源 + 产业对接",
    "fund.kunpeng.description": "面向 35 岁以下青年创业者的创新项目资助。重点支持信息技术、生物医药、新能源等领域。",
    "fund.kunpeng.eligible": "• 35 岁以下青年创业者\n• 具备创新技术或商业模式\n• 项目具有市场化潜力",

    // Fund Card 4: Cyberport
    "fund.cyberport.name": "Cyberport数码港孵化计划",
    "fund.cyberport.tag": "香港旗舰孵化",
    "fund.cyberport.amount": "最高 50 万孵化资助",
    "fund.cyberport.bonus": "免费办公室 + 导师网络",
    "fund.cyberport.description": "香港数码港旗舰孵化项目，专为 AI 和数码科技初创设计，提供全方位创业支援。",
    "fund.cyberport.eligible": "• AI / 数码科技相关项目\n• 香港注册公司或计划在香港注册\n• 具有跨境发展潜力（如 GBA）",

    // Fund Card 5: HKSTP
    "fund.hkstp.name": "科技园Incu-Tech计划",
    "fund.hkstp.tag": "科技企业",
    "fund.hkstp.amount": "最高百万资助 + 资源对接",
    "fund.hkstp.bonus": "科研设施 + 人才网络",
    "fund.hkstp.description": "香港科技园 Incu-Tech 计划，为科技初创提供资助、办公室和科研设施支援。",
    "fund.hkstp.eligible": "• 科技初创企业\n• 持有香港身份证的创业者\n• 具备核心技术或 IP",

    // Fund Card 6: ITF
    "fund.itf.name": "创新及科技基金AI补贴",
    "fund.itf.tag": "创科支援",
    "fund.itf.amount": "最高 70% 算力补贴",
    "fund.itf.bonus": "研发资助 + 技术支持",
    "fund.itf.description": "创新及科技基金下的 AI 专项补贴计划，资助企业采用和开发 AI 技术。",
    "fund.itf.eligible": "• 香港注册的中小企\n• AI 技术应用或研发项目\n• 具有技术团队或合作伙伴",

    // Fund Card 7: GBA
    "fund.gba.name": "大湾区青年创业基金",
    "fund.gba.tag": "跨境创业",
    "fund.gba.amount": "香港青年大湾区创业专项资助",
    "fund.gba.bonus": "额外配套奖励 + 落地支援",
    "fund.gba.description": "专为香港青年在大湾区创业设立的专项基金，提供资金和落地支援。",
    "fund.gba.eligible": "• 香港永久居民\n• 在大湾区内内地城市创业\n• 18-40 岁青年创业者",

    // Fund Card 8: 粵港澳青年
    "fund.youth.name": "粤港澳青年创业计划",
    "fund.youth.tag": "青年创业",
    "fund.youth.amount": "生活补贴 + 创业支援",
    "fund.youth.bonus": "孵化服务 + 导师指导",
    "fund.youth.description": "支持粤港澳三地青年在内地创业的综合资助计划，包含生活补贴和创业支援。",
    "fund.youth.eligible": "• 粤港澳三地青年（18-45岁）\n• 在内地创业的港澳青年\n• 已开展创业项目或已有商业计划",

    // Fund process
    "fund.process.title": "申请流程",
    "fund.process.step1.title": "评估配对",
    "fund.process.step1.desc": "根据你的项目和背景，评估最合适的资助方案",
    "fund.process.step2.title": "准备文件",
    "fund.process.step2.desc": "协助准备商业计划书、财务预测等申请文件",
    "fund.process.step3.title": "递交申请",
    "fund.process.step3.desc": "代为递交申请，确保资料完整合规",
    "fund.process.step4.title": "跟进管理",
    "fund.process.step4.desc": "跟进审批进度，及时补充材料直至获批",

    // Fund docs
    "fund.docs.title": "必备文件清单",
    "fund.docs.business": "商业计划书（Word/PDF）",
    "fund.docs.reg": "公司注册证书副本",
    "fund.docs.id": "创业者身份证证明文件",
    "fund.docs.financial": "财务预测或现有财务报表",
    "fund.docs.tech": "技术/产品介绍（如有）",
    "fund.docs.other": "其他辅助材料（专利、奖项、合作意向书等）",

    // FreeResources
    "free.title": "免费资源",
    "free.subtitle": "回答几条简单问题，立即知道哪个资助啱你",
    "free.cta": "立即评估资格",
    "free.tryAI": "试用 AI 生成文件",
    "free.ready": "准备好开始？",
    "free.pricing": "查看定价",
    "free.consult": "免费咨询",

    // Footer
    "footer.company": "Core Machine Limited",
    "footer.tagline": "港澳青年北上前海创业加速器",
    "footer.description": "专业的中港创业落地服务平台",
    "footer.contact.title": "联系我们",
    "footer.contact.email": "iocoremachine@gmail.com",
    "footer.contact.website": "coremachine.io",
    "footer.services.title": "服务",
    "footer.services.registration": "公司注册",
    "footer.services.subsidy": "补贴申请",
    "footer.services.ai": "AI 工具",
    "footer.services.marketing": "内容营销",
    "footer.resources.title": "资源",
    "footer.resources.templates": "免费模板",
    "footer.resources.blog": "创业指南",
    "footer.resources.faq": "常见问题",
    "footer.legal.title": "法律",
    "footer.legal.terms": "服务条款",
    "footer.legal.privacy": "隐私政策",
    "footer.copyright": "© 2026 Core Machine Limited. 版权所有。",
  },
};

// ========== Provider ==========
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language");
      return (saved === "zh-CN" || saved === "zh-HK") ? saved : "zh-HK";
    }
    return "zh-HK";
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("language", language);
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
